<?php
/**
 * Space48_PromoSashes
 *
 * @category    Space48
 * @package     Space48_PromoSashes
 * @Date        03/2017
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      @diazwatson
 */
?>
<?php /** @var $block Space48\PromoSashes\Block\Sash */ ?>
<img class="product_list_promosashes" src="<?= $block->getViewFileUrl('Space48_PromoSashes::images/new.png') ?>"
     alt="<?= __('new') ?>" title="<?= __('new') ?>">
